input_stream: "pipeline_input"
output_stream: "pipeline_output"

node {
  calculator: "OpenVINOModelServerSessionCalculator"
  output_side_packet: "SESSION:session"
  node_options {
    [type.googleapis.com/mediapipe.OpenVINOModelServerSessionCalculatorOptions] {
      servable_name: "iris_pipeline"
    }
  }
}

node {
  calculator: "OpenVINOInferenceCalculator"
  input_side_packet: "SESSION:session"
  input_stream: "A:pipeline_input"
  output_stream: "B:pipeline_output"
  node_options {
    [type.googleapis.com/mediapipe.OpenVINOInferenceCalculatorOptions] {
      tag_to_input_tensor_names {
        key: "A"
        value: "input"
      }
      tag_to_output_tensor_names {
        key: "B"
        value: "output"
      }
    }
  }
}