FROM centos:7

ARG INSTALL_DIR=/opt/intel/openvino
ARG TEMP_DIR=/tmp/openvino_installer

ARG DL_INSTALL_DIR=/opt/intel/openvino/deployment_tools
ARG DL_DIR=/tmp
ARG https_proxy

ENV TEMP_DIR $TEMP_DIR
ARG DLDT_PACKAGE_URL
ARG OPENCL_PACKAGE_URL=http://registrationcenter-download.intel.com/akdlm/irc_nas/vcp/15532/l_opencl_p_18.1.0.015.tgz

RUN yum install -y \
    python3-pip \
    usbutils

RUN mkdir -p $TEMP_DIR && \
    curl $OPENCL_PACKAGE_URL -o $TEMP_DIR/l_opencl.tgz && \
    cd $TEMP_DIR/ && \
    tar -zxf l_opencl.tgz && \
    rpm -Uh l_opencl_p*/rpm/* --nodeps && \
    rm -Rf $TEMP_DIR/*

# Tested with OpenVINO 2020.2
RUN curl $DLDT_PACKAGE_URL -o $TEMP_DIR/l_openvino.tgz && \
    cd $TEMP_DIR/ && \
    tar -zxf l_openvino.tgz && \
    cd l_openvino_toolkit* && \
    sed -i 's/decline/accept/g' silent.cfg && \
    ./install.sh -s silent.cfg --ignore-signature && \
    rm -Rf $TEMP_DIR $INSTALL_DIR/install_dependencies $INSTALL_DIR/uninstall* /tmp/* $DL_INSTALL_DIR/documentation $DL_INSTALL_DIR/inference_engine/samples \
    $DL_INSTALL_DIR/demo $DL_INSTALL_DIR/model_optimizer $DL_INSTALL_DIR/open_model_zoo $DL_INSTALL_DIR/tools \
    $INSTALL_DIR/python/python2.7 $INSTALL_DIR/python/python3.4 $INSTALL_DIR/python/python3.5 $INSTALL_DIR/python/python3.7 \
    $INSTALL_DIR/openvino_toolkit_uninstaller $INSTALL_DIR/data_processing $INSTALL_DIR/opencv

ENV PYTHONPATH="$INSTALL_DIR/python/python3.6:$INSTALL_DIR/python/python3"
ENV LD_LIBRARY_PATH="$DL_INSTALL_DIR/inference_engine/external/tbb/lib:$DL_INSTALL_DIR/inference_engine/external/mkltiny_lnx/lib:$DL_INSTALL_DIR/inference_engine/external/hddl/lib:$DL_INSTALL_DIR/inference_engine/lib/intel64:$DL_INSTALL_DIR/ngraph/lib"

WORKDIR /ie-serving-py

COPY start_server.sh setup.py version requirements.txt /ie-serving-py/
RUN python3 -m venv .venv && . .venv/bin/activate &&  pip3 install --upgrade pip && pip3 install --no-cache-dir -r requirements.txt

ADD https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/1/vehicle-detection-adas-binary-0001/FP32-INT1/vehicle-detection-adas-binary-0001.bin /opt/models/vehicle_detection_adas/1/
ADD https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/1/vehicle-detection-adas-binary-0001/FP32-INT1/vehicle-detection-adas-binary-0001.xml /opt/models/vehicle_detection_adas/1/
ADD https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/1/vehicle-attributes-recognition-barrier-0039/FP32/vehicle-attributes-recognition-barrier-0039.bin /opt/models/vehicle_attributes/1/
ADD https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/1/vehicle-attributes-recognition-barrier-0039/FP32/vehicle-attributes-recognition-barrier-0039.xml /opt/models/vehicle_attributes/1/
ADD https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/1/age-gender-recognition-retail-0013/FP32/age-gender-recognition-retail-0013.bin /opt/models/age_gender_recognition/1/
ADD https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/1/age-gender-recognition-retail-0013/FP32/age-gender-recognition-retail-0013.xml /opt/models/age_gender_recognition/1/
ADD https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/1/emotions-recognition-retail-0003/FP32/emotions-recognition-retail-0003.bin /opt/models/emotions_recognition/1/
ADD https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/1/emotions-recognition-retail-0003/FP32/emotions-recognition-retail-0003.xml /opt/models/emotions_recognition/1/
ADD https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/3/person-vehicle-bike-detection-crossroad-0078/FP32/person-vehicle-bike-detection-crossroad-0078.bin /opt/models/person_vehicle_bike_detection/1/
ADD https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/3/person-vehicle-bike-detection-crossroad-0078/FP32/person-vehicle-bike-detection-crossroad-0078.xml /opt/models/person_vehicle_bike_detection/1/
ADD https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/3/face-detection-adas-0001/FP32/face-detection-adas-0001.bin /opt/models/face_detection_adas/1/
ADD https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/3/face-detection-adas-0001/FP32/face-detection-adas-0001.xml /opt/models/face_detection_adas/1/
# ADD third_party /third_party/
COPY ie_serving /ie-serving-py/ie_serving
COPY extras/ams_wrapper /ams_wrapper
COPY extras/ams_models /opt/ams_models

RUN . .venv/bin/activate && pip3 install . && chmod +x /ams_wrapper/start_ams.sh

