FROM openvino/ubuntu18_runtime
USER root
RUN apt-get update && apt-get install -y python3-dev python3-venv
WORKDIR /ie-serving-py
COPY start_server.sh setup.py version /ie-serving-py/
COPY ie_serving /ie-serving-py/ie_serving
RUN chown -R openvino .
USER openvino
COPY requirements.txt /ie-serving-py/
RUN python3 -m venv .venv && \
    . .venv/bin/activate && \
    pip3 install --upgrade pip && \
    pip3 --no-cache-dir install -r requirements.txt
RUN . .venv/bin/activate && pip3 install .
ENV PYTHONPATH=/opt/intel/openvino/python/python3.6:/opt/intel/openvino/python/python3
ARG OV_PATH=/opt/intel/openvino/deployment_tools
ENV LD_LIBRARY_PATH=""
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OV_PATH/ngraph/lib:
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OV_PATH/inference_engine/external/gna/lib:
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OV_PATH/inference_engine/external/mkltiny_lnx/lib:
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OV_PATH/inference_engine/external/tbb/lib:
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OV_PATH/inference_engine/lib/intel64