FROM ubuntu:18.04

ARG INSTALL_DIR=/opt/intel/openvino
ARG TEMP_DIR=/tmp/openvino_installer

ARG DL_INSTALL_DIR=/opt/intel/openvino/deployment_tools
ARG DL_DIR=/tmp
ARG https_proxy

ENV TEMP_DIR $TEMP_DIR
ARG DLDT_PACKAGE_URL
RUN apt-get update && apt-get install -y --no-install-recommends \
    cpio \
    libpython3.6 \
    python3-pip \
    python3-venv \
    usbutils \
    virtualenv \
    libboost-filesystem1.65.1 \
    libboost-thread1.65.1 \
    libjson-c3 \
    wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Tested with OpenVINO 2020.1
RUN mkdir -p $TEMP_DIR && cd $TEMP_DIR/ && \
    wget $DLDT_PACKAGE_URL && \
    tar -zxf l_openvino_toolkit*.tgz && \
    cd l_openvino_toolkit* && \
    sed -i 's/decline/accept/g' silent.cfg && \
    sed -i "s/COMPONENTS=DEFAULTS/COMPONENTS=intel-openvino-ie-sdk-ubuntu-bionic__x86_64;intel-openvino-ie-rt-cpu-ubuntu-bionic__x86_64/g" silent.cfg && \    
    ./install.sh -s silent.cfg --ignore-signature && \
    rm -Rf $TEMP_DIR $INSTALL_DIR/install_dependencies $INSTALL_DIR/uninstall* /tmp/* $DL_INSTALL_DIR/documentation $DL_INSTALL_DIR/inference_engine/samples \
    $DL_INSTALL_DIR/demo $DL_INSTALL_DIR/model_optimizer $DL_INSTALL_DIR/open_model_zoo $DL_INSTALL_DIR/tools \
    $INSTALL_DIR/python/python2.7 $INSTALL_DIR/python/python3.4 $INSTALL_DIR/python/python3.5 $INSTALL_DIR/python/python3.7 \
    $INSTALL_DIR/openvino_toolkit_uninstaller

ENV PYTHONPATH="$INSTALL_DIR/python/python3.6:$INSTALL_DIR/python/python3"
ENV LD_LIBRARY_PATH="$DL_INSTALL_DIR/inference_engine/external/tbb/lib:$DL_INSTALL_DIR/inference_engine/external/mkltiny_lnx/lib:$DL_INSTALL_DIR/inference_engine/external/hddl/lib:$DL_INSTALL_DIR/inference_engine/lib/intel64:$DL_INSTALL_DIR/ngraph/lib"

WORKDIR /ie-serving-py

COPY start_server.sh setup.py version requirements.txt /ie-serving-py/
RUN virtualenv -p python3 .venv && . .venv/bin/activate && pip3 install --no-cache-dir -r requirements.txt

RUN mkdir -p /opt/models/vehicle_detection_adas/1 && cd /opt/models/vehicle_detection_adas/1 && \
    wget https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/1/vehicle-detection-adas-binary-0001/FP32-INT1/vehicle-detection-adas-binary-0001.bin && \
    wget https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/1/vehicle-detection-adas-binary-0001/FP32-INT1/vehicle-detection-adas-binary-0001.xml && \
    mkdir -p /opt/models/vehicle_attributes/1 && cd /opt/models/vehicle_attributes/1 && \
    wget https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/1/vehicle-attributes-recognition-barrier-0039/FP32/vehicle-attributes-recognition-barrier-0039.bin && \
    wget https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/1/vehicle-attributes-recognition-barrier-0039/FP32/vehicle-attributes-recognition-barrier-0039.xml

COPY ie_serving /ie-serving-py/ie_serving
COPY extras/ams_wrapper /ams_wrapper
COPY extras/ams_models /opt/ams_models

RUN . .venv/bin/activate && pip3 install . && chmod +x /ams_wrapper/start_ams.sh