FROM openvino/model_server:2021.1-gpu
USER root
ARG https_proxy

RUN yum install -y \
    python3-pip

WORKDIR /ams_wrapper/
COPY extras/ams_wrapper/start_ams.py /ams_wrapper/start_ams.py
COPY extras/ams_wrapper/src /ams_wrapper/src
COPY extras/ams_wrapper/tests/invalid_startup /ams_wrapper/tests/invalid_startup
COPY extras/ams_models /opt/ams_models
COPY extras/ams_wrapper/requirements.txt /ams_wrapper/
RUN pip3 install --upgrade pip && pip3 install --no-cache-dir -r /ams_wrapper/requirements.txt

RUN chmod +x /ams_wrapper/start_ams.py
ADD https://download.01.org/opencv/2021/openvinotoolkit/2021.1/open_model_zoo/models_bin/1/vehicle-detection-adas-0002/FP32/vehicle-detection-adas-0002.bin /opt/models/vehicle_detection_adas/1/
ADD https://download.01.org/opencv/2021/openvinotoolkit/2021.1/open_model_zoo/models_bin/1/vehicle-detection-adas-0002/FP32/vehicle-detection-adas-0002.xml /opt/models/vehicle_detection_adas/1/
ADD https://download.01.org/opencv/2021/openvinotoolkit/2021.1/open_model_zoo/models_bin/1/vehicle-attributes-recognition-barrier-0039/FP32/vehicle-attributes-recognition-barrier-0039.bin /opt/models/vehicle_attributes/1/
ADD https://download.01.org/opencv/2021/openvinotoolkit/2021.1/open_model_zoo/models_bin/1/vehicle-attributes-recognition-barrier-0039/FP32/vehicle-attributes-recognition-barrier-0039.xml /opt/models/vehicle_attributes/1/
ADD https://download.01.org/opencv/2021/openvinotoolkit/2021.1/open_model_zoo/models_bin/1/person-vehicle-bike-detection-crossroad-0078/FP32/person-vehicle-bike-detection-crossroad-0078.bin /opt/models/person_vehicle_bike_detection/1/
ADD https://download.01.org/opencv/2021/openvinotoolkit/2021.1/open_model_zoo/models_bin/1/person-vehicle-bike-detection-crossroad-0078/FP32/person-vehicle-bike-detection-crossroad-0078.xml /opt/models/person_vehicle_bike_detection/1/
ADD https://download.01.org/opencv/2021/openvinotoolkit/2021.1/open_model_zoo/models_bin/1/face-detection-adas-0001/FP32/face-detection-adas-0001.bin /opt/models/face_detection_adas/1/
ADD https://download.01.org/opencv/2021/openvinotoolkit/2021.1/open_model_zoo/models_bin/1/face-detection-adas-0001/FP32/face-detection-adas-0001.xml /opt/models/face_detection_adas/1/
RUN chown -R ovms /opt/models/
#USER ovms
#ENTRYPOINT ["/ams_wrapper/start_ams.py"]
