FROM registry.access.redhat.com/ubi8/ubi:8.4
RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && yum update -d6 -y && yum install -d6 -y gcc-c++ wget make unzip
COPY Makefile /src/example/SampleCustomLoader/
COPY sampleCustLoader.cpp /src/example/SampleCustomLoader/
COPY customloaderinterface.hpp /src/
WORKDIR /src/example/SampleCustomLoader
RUN make all