syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

message ByteTrackCalculatorOptions {
  extend mediapipe.CalculatorOptions {
    optional ByteTrackCalculatorOptions ext = 247258241;
  }
  optional float matching_threshold = 2 [default = 0.8];
  optional int32 track_buffer = 3 [default = 30];
  optional float track_high_threshold = 4 [default = 0.25];
  optional float track_low_threshold = 5 [default = 0.1];
  optional float new_track_threshold = 6 [default = 0.25];
  optional bool fuse_score = 7 [default = true];
}
