#
# Copyright (c) 2026 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ARG BASE_IMAGE=ubuntu:24.04
ARG OVMS_TEST_IMAGE=openvino/model_server:latest-test
ARG OVMS_IMAGE=openvino/model_server:latest

FROM $OVMS_IMAGE as ovms_image
FROM $OVMS_TEST_IMAGE as ovms_test_image
FROM $BASE_IMAGE as base_image

ARG OVMS_DEPENDENCIES="libcurl4-openssl-dev libpugixml1v5 libtbb12 libxml2"
RUN apt-get update && apt-get install -y --no-install-recommends ${OVMS_DEPENDENCIES} && rm -rf /var/lib/apt/lists/*

WORKDIR /
COPY ovms/ ovms/

ENV LD_LIBRARY_PATH=/ovms/lib

RUN /ovms/bin/ovms --version

ARG TOOLS_DEPENDENCIES="build-essential"
RUN apt-get update && apt-get install -y --no-install-recommends ${TOOLS_DEPENDENCIES} && rm -rf /var/lib/apt/lists/*

# Enable GPU
ARG INSTALL_DRIVER_VERSION="25.35.35096"
COPY install_ubuntu_gpu_drivers.sh /tmp/install_ubuntu_gpu_drivers.sh
RUN chmod 775 /tmp/install_ubuntu_gpu_drivers.sh && /tmp/install_ubuntu_gpu_drivers.sh

#COPY install_va.sh /tmp/install_va.sh
#RUN chmod 775 /tmp/install_va.sh && /tmp/install_va.sh
