#
# Copyright (c) 2026 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ARG BASE_IMAGE=registry.access.redhat.com/ubi9/ubi:9.7
ARG OVMS_TEST_IMAGE=openvino-model-server:latest-test
ARG OVMS_IMAGE=registry.connect.redhat.com/intel/openvino-model-server:latest

FROM $OVMS_IMAGE as ovms_image
FROM $OVMS_TEST_IMAGE as ovms_test_image
FROM $BASE_IMAGE as base_image

# libtbb is now available in /ovms/lib
#ARG OVMS_DEPENDENCIES="https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/Packages/tbb-2020.3-8.el9.x86_64.rpm"
#RUN dnf install -y pkg-config && rpm -ivh ${OVMS_DEPENDENCIES}

WORKDIR /
COPY ovms/ ovms/

ENV LD_LIBRARY_PATH=/ovms/lib

RUN /ovms/bin/ovms --version
RUN dnf install -y https://rpmfind.net/linux/centos-stream/9-stream/BaseOS/x86_64/os/Packages/libnl3-3.11.0-1.el9.x86_64.rpm && dnf clean all
RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && dnf clean all && \
    yum update -d6 -y && yum install -d6 -y gcc-c++
RUN dnf install -y pkg-config && rpm -ivh https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/Packages/opencl-headers-3.0-6.20201007gitd65bcc5.el9.noarch.rpm && dnf clean all

# Enable GPU
ARG INSTALL_DRIVER_VERSION="24.52.32224"
ARG DNF_TOOL="dnf"
COPY install_redhat_gpu_drivers.sh /tmp/install_redhat_gpu_drivers.sh
RUN chmod 775 /tmp/install_redhat_gpu_drivers.sh && /tmp/install_redhat_gpu_drivers.sh

# use for debug with GPU target device
#RUN yum update -d6 -y && yum install -d6 -y clinfo
