# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ie_serving/messaging/data_attributes.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ie_serving/messaging/data_attributes.proto',
  package='ovms_ipc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n*ie_serving/messaging/data_attributes.proto\x12\x08ovms_ipc\"3\n\x0fNumpyAttributes\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\x11\n\tdata_type\x18\x02 \x01(\t\"4\n\x10StringAttributes\x12\x0e\n\x06length\x18\x01 \x01(\x05\x12\x10\n\x08\x65ncoding\x18\x02 \x01(\t\"\"\n\x10\x42inaryAttributes\x12\x0e\n\x06length\x18\x01 \x01(\x05\x62\x06proto3'
)




_NUMPYATTRIBUTES = _descriptor.Descriptor(
  name='NumpyAttributes',
  full_name='ovms_ipc.NumpyAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shape', full_name='ovms_ipc.NumpyAttributes.shape', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_type', full_name='ovms_ipc.NumpyAttributes.data_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=107,
)


_STRINGATTRIBUTES = _descriptor.Descriptor(
  name='StringAttributes',
  full_name='ovms_ipc.StringAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='ovms_ipc.StringAttributes.length', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encoding', full_name='ovms_ipc.StringAttributes.encoding', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=161,
)


_BINARYATTRIBUTES = _descriptor.Descriptor(
  name='BinaryAttributes',
  full_name='ovms_ipc.BinaryAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='ovms_ipc.BinaryAttributes.length', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=197,
)

DESCRIPTOR.message_types_by_name['NumpyAttributes'] = _NUMPYATTRIBUTES
DESCRIPTOR.message_types_by_name['StringAttributes'] = _STRINGATTRIBUTES
DESCRIPTOR.message_types_by_name['BinaryAttributes'] = _BINARYATTRIBUTES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NumpyAttributes = _reflection.GeneratedProtocolMessageType('NumpyAttributes', (_message.Message,), {
  'DESCRIPTOR' : _NUMPYATTRIBUTES,
  '__module__' : 'ie_serving.messaging.data_attributes_pb2'
  # @@protoc_insertion_point(class_scope:ovms_ipc.NumpyAttributes)
  })
_sym_db.RegisterMessage(NumpyAttributes)

StringAttributes = _reflection.GeneratedProtocolMessageType('StringAttributes', (_message.Message,), {
  'DESCRIPTOR' : _STRINGATTRIBUTES,
  '__module__' : 'ie_serving.messaging.data_attributes_pb2'
  # @@protoc_insertion_point(class_scope:ovms_ipc.StringAttributes)
  })
_sym_db.RegisterMessage(StringAttributes)

BinaryAttributes = _reflection.GeneratedProtocolMessageType('BinaryAttributes', (_message.Message,), {
  'DESCRIPTOR' : _BINARYATTRIBUTES,
  '__module__' : 'ie_serving.messaging.data_attributes_pb2'
  # @@protoc_insertion_point(class_scope:ovms_ipc.BinaryAttributes)
  })
_sym_db.RegisterMessage(BinaryAttributes)


# @@protoc_insertion_point(module_scope)
