# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_attributes.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data_attributes.proto',
  package='ovms_ipc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x15\x64\x61ta_attributes.proto\x12\x08ovms_ipc\"\xfd\x02\n\x0e\x44\x61taAttributes\x12\x44\n\x10numpy_attributes\x18\x01 \x01(\x0b\x32(.ovms_ipc.DataAttributes.NumpyAttributesH\x00\x12\x46\n\x11string_attributes\x18\x02 \x01(\x0b\x32).ovms_ipc.DataAttributes.StringAttributesH\x00\x12\x46\n\x11\x62inary_attributes\x18\x03 \x01(\x0b\x32).ovms_ipc.DataAttributes.BinaryAttributesH\x00\x1a\x33\n\x0fNumpyAttributes\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\x11\n\tdata_type\x18\x02 \x01(\t\x1a\x34\n\x10StringAttributes\x12\x0e\n\x06length\x18\x01 \x01(\x05\x12\x10\n\x08\x65ncoding\x18\x02 \x01(\t\x1a\"\n\x10\x42inaryAttributes\x12\x0e\n\x06length\x18\x01 \x01(\x05\x42\x06\n\x04typeb\x06proto3'
)




_DATAATTRIBUTES_NUMPYATTRIBUTES = _descriptor.Descriptor(
  name='NumpyAttributes',
  full_name='ovms_ipc.DataAttributes.NumpyAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shape', full_name='ovms_ipc.DataAttributes.NumpyAttributes.shape', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_type', full_name='ovms_ipc.DataAttributes.NumpyAttributes.data_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=319,
)

_DATAATTRIBUTES_STRINGATTRIBUTES = _descriptor.Descriptor(
  name='StringAttributes',
  full_name='ovms_ipc.DataAttributes.StringAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='ovms_ipc.DataAttributes.StringAttributes.length', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encoding', full_name='ovms_ipc.DataAttributes.StringAttributes.encoding', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=373,
)

_DATAATTRIBUTES_BINARYATTRIBUTES = _descriptor.Descriptor(
  name='BinaryAttributes',
  full_name='ovms_ipc.DataAttributes.BinaryAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='ovms_ipc.DataAttributes.BinaryAttributes.length', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=409,
)

_DATAATTRIBUTES = _descriptor.Descriptor(
  name='DataAttributes',
  full_name='ovms_ipc.DataAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numpy_attributes', full_name='ovms_ipc.DataAttributes.numpy_attributes', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_attributes', full_name='ovms_ipc.DataAttributes.string_attributes', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='binary_attributes', full_name='ovms_ipc.DataAttributes.binary_attributes', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DATAATTRIBUTES_NUMPYATTRIBUTES, _DATAATTRIBUTES_STRINGATTRIBUTES, _DATAATTRIBUTES_BINARYATTRIBUTES, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='ovms_ipc.DataAttributes.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=36,
  serialized_end=417,
)

_DATAATTRIBUTES_NUMPYATTRIBUTES.containing_type = _DATAATTRIBUTES
_DATAATTRIBUTES_STRINGATTRIBUTES.containing_type = _DATAATTRIBUTES
_DATAATTRIBUTES_BINARYATTRIBUTES.containing_type = _DATAATTRIBUTES
_DATAATTRIBUTES.fields_by_name['numpy_attributes'].message_type = _DATAATTRIBUTES_NUMPYATTRIBUTES
_DATAATTRIBUTES.fields_by_name['string_attributes'].message_type = _DATAATTRIBUTES_STRINGATTRIBUTES
_DATAATTRIBUTES.fields_by_name['binary_attributes'].message_type = _DATAATTRIBUTES_BINARYATTRIBUTES
_DATAATTRIBUTES.oneofs_by_name['type'].fields.append(
  _DATAATTRIBUTES.fields_by_name['numpy_attributes'])
_DATAATTRIBUTES.fields_by_name['numpy_attributes'].containing_oneof = _DATAATTRIBUTES.oneofs_by_name['type']
_DATAATTRIBUTES.oneofs_by_name['type'].fields.append(
  _DATAATTRIBUTES.fields_by_name['string_attributes'])
_DATAATTRIBUTES.fields_by_name['string_attributes'].containing_oneof = _DATAATTRIBUTES.oneofs_by_name['type']
_DATAATTRIBUTES.oneofs_by_name['type'].fields.append(
  _DATAATTRIBUTES.fields_by_name['binary_attributes'])
_DATAATTRIBUTES.fields_by_name['binary_attributes'].containing_oneof = _DATAATTRIBUTES.oneofs_by_name['type']
DESCRIPTOR.message_types_by_name['DataAttributes'] = _DATAATTRIBUTES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataAttributes = _reflection.GeneratedProtocolMessageType('DataAttributes', (_message.Message,), {

  'NumpyAttributes' : _reflection.GeneratedProtocolMessageType('NumpyAttributes', (_message.Message,), {
    'DESCRIPTOR' : _DATAATTRIBUTES_NUMPYATTRIBUTES,
    '__module__' : 'data_attributes_pb2'
    # @@protoc_insertion_point(class_scope:ovms_ipc.DataAttributes.NumpyAttributes)
    })
  ,

  'StringAttributes' : _reflection.GeneratedProtocolMessageType('StringAttributes', (_message.Message,), {
    'DESCRIPTOR' : _DATAATTRIBUTES_STRINGATTRIBUTES,
    '__module__' : 'data_attributes_pb2'
    # @@protoc_insertion_point(class_scope:ovms_ipc.DataAttributes.StringAttributes)
    })
  ,

  'BinaryAttributes' : _reflection.GeneratedProtocolMessageType('BinaryAttributes', (_message.Message,), {
    'DESCRIPTOR' : _DATAATTRIBUTES_BINARYATTRIBUTES,
    '__module__' : 'data_attributes_pb2'
    # @@protoc_insertion_point(class_scope:ovms_ipc.DataAttributes.BinaryAttributes)
    })
  ,
  'DESCRIPTOR' : _DATAATTRIBUTES,
  '__module__' : 'data_attributes_pb2'
  # @@protoc_insertion_point(class_scope:ovms_ipc.DataAttributes)
  })
_sym_db.RegisterMessage(DataAttributes)
_sym_db.RegisterMessage(DataAttributes.NumpyAttributes)
_sym_db.RegisterMessage(DataAttributes.StringAttributes)
_sym_db.RegisterMessage(DataAttributes.BinaryAttributes)


# @@protoc_insertion_point(module_scope)
