# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: endpoint_requests.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='endpoint_requests.proto',
  package='ovms_ipc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x17\x65ndpoint_requests.proto\x12\x08ovms_ipc\"\xce\x01\n\x0f\x45ndpointRequest\x12\x33\n\x0fpredict_request\x18\x01 \x01(\x0b\x32\x18.ovms_ipc.PredictRequestH\x00\x12@\n\x16model_metadata_request\x18\x02 \x01(\x0b\x32\x1e.ovms_ipc.ModelMetadataRequestH\x00\x12<\n\x14model_status_request\x18\x03 \x01(\x0b\x32\x1c.ovms_ipc.ModelStatusRequestH\x00\x42\x06\n\x04type\"\xee\x01\n\x0ePredictRequest\x12\x34\n\tdata_type\x18\x01 \x01(\x0e\x32!.ovms_ipc.PredictRequest.DataType\x12-\n\x06inputs\x18\x02 \x03(\x0b\x32\x1d.ovms_ipc.PredictRequest.Data\x12\x1a\n\x12return_socket_name\x18\x03 \x01(\t\x1a,\n\x04\x44\x61ta\x12\x12\n\ninput_name\x18\x01 \x01(\t\x12\x10\n\x08shm_name\x18\x02 \x01(\t\"-\n\x08\x44\x61taType\x12\t\n\x05NUMPY\x10\x00\x12\n\n\x06STRING\x10\x02\x12\n\n\x06\x42INARY\x10\x03\"1\n\x14ModelMetadataRequest\x12\x19\n\x11requested_version\x18\x01 \x01(\x05\"/\n\x12ModelStatusRequest\x12\x19\n\x11requested_version\x18\x01 \x01(\x05\x62\x06proto3'
)



_PREDICTREQUEST_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='ovms_ipc.PredictRequest.DataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NUMPY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STRING', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BINARY', index=2, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=440,
  serialized_end=485,
)
_sym_db.RegisterEnumDescriptor(_PREDICTREQUEST_DATATYPE)


_ENDPOINTREQUEST = _descriptor.Descriptor(
  name='EndpointRequest',
  full_name='ovms_ipc.EndpointRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='predict_request', full_name='ovms_ipc.EndpointRequest.predict_request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_metadata_request', full_name='ovms_ipc.EndpointRequest.model_metadata_request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_status_request', full_name='ovms_ipc.EndpointRequest.model_status_request', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='ovms_ipc.EndpointRequest.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=38,
  serialized_end=244,
)


_PREDICTREQUEST_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='ovms_ipc.PredictRequest.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_name', full_name='ovms_ipc.PredictRequest.Data.input_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shm_name', full_name='ovms_ipc.PredictRequest.Data.shm_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=438,
)

_PREDICTREQUEST = _descriptor.Descriptor(
  name='PredictRequest',
  full_name='ovms_ipc.PredictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_type', full_name='ovms_ipc.PredictRequest.data_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='ovms_ipc.PredictRequest.inputs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='return_socket_name', full_name='ovms_ipc.PredictRequest.return_socket_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PREDICTREQUEST_DATA, ],
  enum_types=[
    _PREDICTREQUEST_DATATYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=485,
)


_MODELMETADATAREQUEST = _descriptor.Descriptor(
  name='ModelMetadataRequest',
  full_name='ovms_ipc.ModelMetadataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requested_version', full_name='ovms_ipc.ModelMetadataRequest.requested_version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=487,
  serialized_end=536,
)


_MODELSTATUSREQUEST = _descriptor.Descriptor(
  name='ModelStatusRequest',
  full_name='ovms_ipc.ModelStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requested_version', full_name='ovms_ipc.ModelStatusRequest.requested_version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=538,
  serialized_end=585,
)

_ENDPOINTREQUEST.fields_by_name['predict_request'].message_type = _PREDICTREQUEST
_ENDPOINTREQUEST.fields_by_name['model_metadata_request'].message_type = _MODELMETADATAREQUEST
_ENDPOINTREQUEST.fields_by_name['model_status_request'].message_type = _MODELSTATUSREQUEST
_ENDPOINTREQUEST.oneofs_by_name['type'].fields.append(
  _ENDPOINTREQUEST.fields_by_name['predict_request'])
_ENDPOINTREQUEST.fields_by_name['predict_request'].containing_oneof = _ENDPOINTREQUEST.oneofs_by_name['type']
_ENDPOINTREQUEST.oneofs_by_name['type'].fields.append(
  _ENDPOINTREQUEST.fields_by_name['model_metadata_request'])
_ENDPOINTREQUEST.fields_by_name['model_metadata_request'].containing_oneof = _ENDPOINTREQUEST.oneofs_by_name['type']
_ENDPOINTREQUEST.oneofs_by_name['type'].fields.append(
  _ENDPOINTREQUEST.fields_by_name['model_status_request'])
_ENDPOINTREQUEST.fields_by_name['model_status_request'].containing_oneof = _ENDPOINTREQUEST.oneofs_by_name['type']
_PREDICTREQUEST_DATA.containing_type = _PREDICTREQUEST
_PREDICTREQUEST.fields_by_name['data_type'].enum_type = _PREDICTREQUEST_DATATYPE
_PREDICTREQUEST.fields_by_name['inputs'].message_type = _PREDICTREQUEST_DATA
_PREDICTREQUEST_DATATYPE.containing_type = _PREDICTREQUEST
DESCRIPTOR.message_types_by_name['EndpointRequest'] = _ENDPOINTREQUEST
DESCRIPTOR.message_types_by_name['PredictRequest'] = _PREDICTREQUEST
DESCRIPTOR.message_types_by_name['ModelMetadataRequest'] = _MODELMETADATAREQUEST
DESCRIPTOR.message_types_by_name['ModelStatusRequest'] = _MODELSTATUSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EndpointRequest = _reflection.GeneratedProtocolMessageType('EndpointRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENDPOINTREQUEST,
  '__module__' : 'endpoint_requests_pb2'
  # @@protoc_insertion_point(class_scope:ovms_ipc.EndpointRequest)
  })
_sym_db.RegisterMessage(EndpointRequest)

PredictRequest = _reflection.GeneratedProtocolMessageType('PredictRequest', (_message.Message,), {

  'Data' : _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
    'DESCRIPTOR' : _PREDICTREQUEST_DATA,
    '__module__' : 'endpoint_requests_pb2'
    # @@protoc_insertion_point(class_scope:ovms_ipc.PredictRequest.Data)
    })
  ,
  'DESCRIPTOR' : _PREDICTREQUEST,
  '__module__' : 'endpoint_requests_pb2'
  # @@protoc_insertion_point(class_scope:ovms_ipc.PredictRequest)
  })
_sym_db.RegisterMessage(PredictRequest)
_sym_db.RegisterMessage(PredictRequest.Data)

ModelMetadataRequest = _reflection.GeneratedProtocolMessageType('ModelMetadataRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODELMETADATAREQUEST,
  '__module__' : 'endpoint_requests_pb2'
  # @@protoc_insertion_point(class_scope:ovms_ipc.ModelMetadataRequest)
  })
_sym_db.RegisterMessage(ModelMetadataRequest)

ModelStatusRequest = _reflection.GeneratedProtocolMessageType('ModelStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODELSTATUSREQUEST,
  '__module__' : 'endpoint_requests_pb2'
  # @@protoc_insertion_point(class_scope:ovms_ipc.ModelStatusRequest)
  })
_sym_db.RegisterMessage(ModelStatusRequest)


# @@protoc_insertion_point(module_scope)
