# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zmq_messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='zmq_messages.proto',
  package='ovms_ipc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12zmq_messages.proto\x12\x08ovms_ipc\"\xce\x01\n\x0f\x45ndpointRequest\x12\x33\n\x0fpredict_request\x18\x01 \x01(\x0b\x32\x18.ovms_ipc.PredictRequestH\x00\x12@\n\x16model_metadata_request\x18\x02 \x01(\x0b\x32\x1e.ovms_ipc.ModelMetadataRequestH\x00\x12<\n\x14model_status_request\x18\x03 \x01(\x0b\x32\x1c.ovms_ipc.ModelStatusRequestH\x00\x42\x06\n\x04type\"\x88\x02\n\x10\x45ndpointResponse\x12\x35\n\x10predict_response\x18\x01 \x01(\x0b\x32\x19.ovms_ipc.PredictResponseH\x00\x12\x42\n\x17model_metadata_response\x18\x02 \x01(\x0b\x32\x1f.ovms_ipc.ModelMetadataResponseH\x00\x12>\n\x15model_status_response\x18\x03 \x01(\x0b\x32\x1d.ovms_ipc.ModelStatusResponseH\x00\x12\x31\n\x0e\x65rror_response\x18\x04 \x01(\x0b\x32\x17.ovms_ipc.ErrorResponseH\x00\x42\x06\n\x04type\"m\n\x0ePredictRequest\x12-\n\x06inputs\x18\x01 \x03(\x0b\x32\x1d.ovms_ipc.PredictRequest.Data\x1a,\n\x04\x44\x61ta\x12\x12\n\ninput_name\x18\x01 \x01(\t\x12\x10\n\x08shm_name\x18\x02 \x01(\t\"q\n\x0fPredictResponse\x12/\n\x07outputs\x18\x01 \x03(\x0b\x32\x1e.ovms_ipc.PredictResponse.Data\x1a-\n\x04\x44\x61ta\x12\x13\n\x0boutput_name\x18\x01 \x01(\t\x12\x10\n\x08shm_name\x18\x02 \x01(\t\".\n\x14ModelMetadataRequest\x12\x16\n\x0emetadata_field\x18\x01 \x01(\x08\"\x17\n\x15ModelMetadataResponse\"*\n\x12ModelStatusRequest\x12\x14\n\x0cstatus_field\x18\x01 \x01(\x08\"\x15\n\x13ModelStatusResponse\"&\n\rErrorResponse\x12\x15\n\rerror_message\x18\x01 \x01(\tb\x06proto3'
)




_ENDPOINTREQUEST = _descriptor.Descriptor(
  name='EndpointRequest',
  full_name='ovms_ipc.EndpointRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='predict_request', full_name='ovms_ipc.EndpointRequest.predict_request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_metadata_request', full_name='ovms_ipc.EndpointRequest.model_metadata_request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_status_request', full_name='ovms_ipc.EndpointRequest.model_status_request', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='ovms_ipc.EndpointRequest.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=33,
  serialized_end=239,
)


_ENDPOINTRESPONSE = _descriptor.Descriptor(
  name='EndpointResponse',
  full_name='ovms_ipc.EndpointResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='predict_response', full_name='ovms_ipc.EndpointResponse.predict_response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_metadata_response', full_name='ovms_ipc.EndpointResponse.model_metadata_response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_status_response', full_name='ovms_ipc.EndpointResponse.model_status_response', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_response', full_name='ovms_ipc.EndpointResponse.error_response', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='ovms_ipc.EndpointResponse.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=242,
  serialized_end=506,
)


_PREDICTREQUEST_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='ovms_ipc.PredictRequest.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_name', full_name='ovms_ipc.PredictRequest.Data.input_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shm_name', full_name='ovms_ipc.PredictRequest.Data.shm_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=573,
  serialized_end=617,
)

_PREDICTREQUEST = _descriptor.Descriptor(
  name='PredictRequest',
  full_name='ovms_ipc.PredictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inputs', full_name='ovms_ipc.PredictRequest.inputs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PREDICTREQUEST_DATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=508,
  serialized_end=617,
)


_PREDICTRESPONSE_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='ovms_ipc.PredictResponse.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='output_name', full_name='ovms_ipc.PredictResponse.Data.output_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shm_name', full_name='ovms_ipc.PredictResponse.Data.shm_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=687,
  serialized_end=732,
)

_PREDICTRESPONSE = _descriptor.Descriptor(
  name='PredictResponse',
  full_name='ovms_ipc.PredictResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='outputs', full_name='ovms_ipc.PredictResponse.outputs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PREDICTRESPONSE_DATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=619,
  serialized_end=732,
)


_MODELMETADATAREQUEST = _descriptor.Descriptor(
  name='ModelMetadataRequest',
  full_name='ovms_ipc.ModelMetadataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata_field', full_name='ovms_ipc.ModelMetadataRequest.metadata_field', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=734,
  serialized_end=780,
)


_MODELMETADATARESPONSE = _descriptor.Descriptor(
  name='ModelMetadataResponse',
  full_name='ovms_ipc.ModelMetadataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=782,
  serialized_end=805,
)


_MODELSTATUSREQUEST = _descriptor.Descriptor(
  name='ModelStatusRequest',
  full_name='ovms_ipc.ModelStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_field', full_name='ovms_ipc.ModelStatusRequest.status_field', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=807,
  serialized_end=849,
)


_MODELSTATUSRESPONSE = _descriptor.Descriptor(
  name='ModelStatusResponse',
  full_name='ovms_ipc.ModelStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=851,
  serialized_end=872,
)


_ERRORRESPONSE = _descriptor.Descriptor(
  name='ErrorResponse',
  full_name='ovms_ipc.ErrorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_message', full_name='ovms_ipc.ErrorResponse.error_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=874,
  serialized_end=912,
)

_ENDPOINTREQUEST.fields_by_name['predict_request'].message_type = _PREDICTREQUEST
_ENDPOINTREQUEST.fields_by_name['model_metadata_request'].message_type = _MODELMETADATAREQUEST
_ENDPOINTREQUEST.fields_by_name['model_status_request'].message_type = _MODELSTATUSREQUEST
_ENDPOINTREQUEST.oneofs_by_name['type'].fields.append(
  _ENDPOINTREQUEST.fields_by_name['predict_request'])
_ENDPOINTREQUEST.fields_by_name['predict_request'].containing_oneof = _ENDPOINTREQUEST.oneofs_by_name['type']
_ENDPOINTREQUEST.oneofs_by_name['type'].fields.append(
  _ENDPOINTREQUEST.fields_by_name['model_metadata_request'])
_ENDPOINTREQUEST.fields_by_name['model_metadata_request'].containing_oneof = _ENDPOINTREQUEST.oneofs_by_name['type']
_ENDPOINTREQUEST.oneofs_by_name['type'].fields.append(
  _ENDPOINTREQUEST.fields_by_name['model_status_request'])
_ENDPOINTREQUEST.fields_by_name['model_status_request'].containing_oneof = _ENDPOINTREQUEST.oneofs_by_name['type']
_ENDPOINTRESPONSE.fields_by_name['predict_response'].message_type = _PREDICTRESPONSE
_ENDPOINTRESPONSE.fields_by_name['model_metadata_response'].message_type = _MODELMETADATARESPONSE
_ENDPOINTRESPONSE.fields_by_name['model_status_response'].message_type = _MODELSTATUSRESPONSE
_ENDPOINTRESPONSE.fields_by_name['error_response'].message_type = _ERRORRESPONSE
_ENDPOINTRESPONSE.oneofs_by_name['type'].fields.append(
  _ENDPOINTRESPONSE.fields_by_name['predict_response'])
_ENDPOINTRESPONSE.fields_by_name['predict_response'].containing_oneof = _ENDPOINTRESPONSE.oneofs_by_name['type']
_ENDPOINTRESPONSE.oneofs_by_name['type'].fields.append(
  _ENDPOINTRESPONSE.fields_by_name['model_metadata_response'])
_ENDPOINTRESPONSE.fields_by_name['model_metadata_response'].containing_oneof = _ENDPOINTRESPONSE.oneofs_by_name['type']
_ENDPOINTRESPONSE.oneofs_by_name['type'].fields.append(
  _ENDPOINTRESPONSE.fields_by_name['model_status_response'])
_ENDPOINTRESPONSE.fields_by_name['model_status_response'].containing_oneof = _ENDPOINTRESPONSE.oneofs_by_name['type']
_ENDPOINTRESPONSE.oneofs_by_name['type'].fields.append(
  _ENDPOINTRESPONSE.fields_by_name['error_response'])
_ENDPOINTRESPONSE.fields_by_name['error_response'].containing_oneof = _ENDPOINTRESPONSE.oneofs_by_name['type']
_PREDICTREQUEST_DATA.containing_type = _PREDICTREQUEST
_PREDICTREQUEST.fields_by_name['inputs'].message_type = _PREDICTREQUEST_DATA
_PREDICTRESPONSE_DATA.containing_type = _PREDICTRESPONSE
_PREDICTRESPONSE.fields_by_name['outputs'].message_type = _PREDICTRESPONSE_DATA
DESCRIPTOR.message_types_by_name['EndpointRequest'] = _ENDPOINTREQUEST
DESCRIPTOR.message_types_by_name['EndpointResponse'] = _ENDPOINTRESPONSE
DESCRIPTOR.message_types_by_name['PredictRequest'] = _PREDICTREQUEST
DESCRIPTOR.message_types_by_name['PredictResponse'] = _PREDICTRESPONSE
DESCRIPTOR.message_types_by_name['ModelMetadataRequest'] = _MODELMETADATAREQUEST
DESCRIPTOR.message_types_by_name['ModelMetadataResponse'] = _MODELMETADATARESPONSE
DESCRIPTOR.message_types_by_name['ModelStatusRequest'] = _MODELSTATUSREQUEST
DESCRIPTOR.message_types_by_name['ModelStatusResponse'] = _MODELSTATUSRESPONSE
DESCRIPTOR.message_types_by_name['ErrorResponse'] = _ERRORRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EndpointRequest = _reflection.GeneratedProtocolMessageType('EndpointRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENDPOINTREQUEST,
  '__module__' : 'zmq_messages_pb2'
  # @@protoc_insertion_point(class_scope:ovms_ipc.EndpointRequest)
  })
_sym_db.RegisterMessage(EndpointRequest)

EndpointResponse = _reflection.GeneratedProtocolMessageType('EndpointResponse', (_message.Message,), {
  'DESCRIPTOR' : _ENDPOINTRESPONSE,
  '__module__' : 'zmq_messages_pb2'
  # @@protoc_insertion_point(class_scope:ovms_ipc.EndpointResponse)
  })
_sym_db.RegisterMessage(EndpointResponse)

PredictRequest = _reflection.GeneratedProtocolMessageType('PredictRequest', (_message.Message,), {

  'Data' : _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
    'DESCRIPTOR' : _PREDICTREQUEST_DATA,
    '__module__' : 'zmq_messages_pb2'
    # @@protoc_insertion_point(class_scope:ovms_ipc.PredictRequest.Data)
    })
  ,
  'DESCRIPTOR' : _PREDICTREQUEST,
  '__module__' : 'zmq_messages_pb2'
  # @@protoc_insertion_point(class_scope:ovms_ipc.PredictRequest)
  })
_sym_db.RegisterMessage(PredictRequest)
_sym_db.RegisterMessage(PredictRequest.Data)

PredictResponse = _reflection.GeneratedProtocolMessageType('PredictResponse', (_message.Message,), {

  'Data' : _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
    'DESCRIPTOR' : _PREDICTRESPONSE_DATA,
    '__module__' : 'zmq_messages_pb2'
    # @@protoc_insertion_point(class_scope:ovms_ipc.PredictResponse.Data)
    })
  ,
  'DESCRIPTOR' : _PREDICTRESPONSE,
  '__module__' : 'zmq_messages_pb2'
  # @@protoc_insertion_point(class_scope:ovms_ipc.PredictResponse)
  })
_sym_db.RegisterMessage(PredictResponse)
_sym_db.RegisterMessage(PredictResponse.Data)

ModelMetadataRequest = _reflection.GeneratedProtocolMessageType('ModelMetadataRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODELMETADATAREQUEST,
  '__module__' : 'zmq_messages_pb2'
  # @@protoc_insertion_point(class_scope:ovms_ipc.ModelMetadataRequest)
  })
_sym_db.RegisterMessage(ModelMetadataRequest)

ModelMetadataResponse = _reflection.GeneratedProtocolMessageType('ModelMetadataResponse', (_message.Message,), {
  'DESCRIPTOR' : _MODELMETADATARESPONSE,
  '__module__' : 'zmq_messages_pb2'
  # @@protoc_insertion_point(class_scope:ovms_ipc.ModelMetadataResponse)
  })
_sym_db.RegisterMessage(ModelMetadataResponse)

ModelStatusRequest = _reflection.GeneratedProtocolMessageType('ModelStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODELSTATUSREQUEST,
  '__module__' : 'zmq_messages_pb2'
  # @@protoc_insertion_point(class_scope:ovms_ipc.ModelStatusRequest)
  })
_sym_db.RegisterMessage(ModelStatusRequest)

ModelStatusResponse = _reflection.GeneratedProtocolMessageType('ModelStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _MODELSTATUSRESPONSE,
  '__module__' : 'zmq_messages_pb2'
  # @@protoc_insertion_point(class_scope:ovms_ipc.ModelStatusResponse)
  })
_sym_db.RegisterMessage(ModelStatusResponse)

ErrorResponse = _reflection.GeneratedProtocolMessageType('ErrorResponse', (_message.Message,), {
  'DESCRIPTOR' : _ERRORRESPONSE,
  '__module__' : 'zmq_messages_pb2'
  # @@protoc_insertion_point(class_scope:ovms_ipc.ErrorResponse)
  })
_sym_db.RegisterMessage(ErrorResponse)


# @@protoc_insertion_point(module_scope)
