//*****************************************************************************
// Copyright 2026 Intel Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//*****************************************************************************

// Plugin entry point for registering MediaPipe Python calculators
// This file is compiled into libpython_calculators.so and can be loaded
// dynamically at runtime via dlopen/LoadLibrary

// Forward declarations of registration functions from calculator files
namespace mediapipe {
// These are generated by REGISTER_CALCULATOR macro but we need explicit
// declarations to call them from this plugin entry point
class PythonExecutorCalculator;
}  // namespace mediapipe

namespace ovms {

#if defined(_WIN32)
#define PYTHON_CALCULATORS_EXPORT __declspec(dllexport)
#else
#define PYTHON_CALCULATORS_EXPORT __attribute__((visibility("default")))
#endif

// Entry point function called by the main binary to register all Python calculators
// This function is exported and called via dlsym after loading the plugin
extern "C" PYTHON_CALCULATORS_EXPORT void registerPythonCalculators() {
    // The REGISTER_CALCULATOR macro creates static initializers that run
    // when this .so is loaded. By the time this function is called, those
    // initializers have already executed and registered the calculators.
    // This function serves as an explicit synchronization point.
    // No additional code needed here - the work is done by static initializers.
}

#undef PYTHON_CALCULATORS_EXPORT

}  // namespace ovms
