input_stream: "inference_input"
output_stream: "inference_output"

node {
  calculator: "InferenceCalculator"
  input_stream: "inference_input"
  output_stream: "inference_output"
  options: {
    [type.googleapis.com/openvino.CalculatorOptions] {
      model_name: "iris_pipeline"
      signature_name: "serving_default"
    }
  }
}
