FROM python:3.8-slim

WORKDIR /usr/src/app
COPY app.py .
COPY client_requirements.txt .
RUN pip install --no-cache-dir -r client_requirements.txt
EXPOSE 7860
ENV GRADIO_SERVER_NAME="0.0.0.0"

CMD ["python", "app.py"]