#
# Copyright 2023 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
input_stream: "in_not_used"
output_stream: "out_string"
output_stream: "out_int64"
output_stream: "out_bool"
node {
  calculator: "InputSidePacketUserTestCalc"
  input_side_packet: "INPUT_SIDE_PACKET_STRING:string_param"
  input_side_packet: "INPUT_SIDE_PACKET_INT64:int64_param"
  input_side_packet: "INPUT_SIDE_PACKET_BOOL:bool_param"
  input_stream: "INPUT_FP32:in_not_used"
  output_stream: "OUTPUT_UINT8:out_string"
  output_stream: "OUTPUT_INT64:out_int64"
  output_stream: "OUTPUT_BOOL:out_bool"
}

