apiVersion: v1
kind: ReplicationController
metadata:
  name: gs-openvino
spec:
  replicas: 3
  selector:
    role: model_server
  template:
    metadata:
      labels:
        role: model_server
    spec:
      containers:
      - name: openvino-model-server
        image: [your openvino model server image]
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/credentials/key.json"
        volumeMounts:
        - name: gcp-credentials
          mountPath: "/etc/credentials"
        command: ["/ie-serving-py/start_server.sh"]
        args: ["ie_serving", "model", "--model_path", "gs://bucket/model_path", "--model_name", "resnet", "--port", "80"]
        ports:
          - name: grpc
            containerPort: 80
      volumes:
      - name: gcp-credentials
        secret:
          secretName: gcp-credentials
