---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovms
  labels:
    app: ovms
spec:
  selector:
    matchLabels:
       app: ovms
  replicas: 2
  template:
    metadata:
      labels:
        app: ovms
    spec:
      containers:
      - name: ovms-resnet
        image: intelaipg/openvino-model-server:latest
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: "GOOGLE_APPLICATION_CREDENTIALS"
          value: ""
        command: ["/ie-serving-py/start_server.sh"]
        args: ["ie_serving", "model", "--model_path", "gs://intelai_public_models/resnet_50_i8", "--model_name", "resnet", "--port", "80", "--batch_size", "auto"]
---
apiVersion: v1
kind: Service
metadata:
  name: ovms-resnet
spec:
  selector:
    app: ovms
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
