{
 "title": "Processing time",
 "time": { "from": "2024-12-23T13:25:13.000Z", "to": "2024-12-23T14:04:12.587Z" },
 "panels": [
  {
   "title": "Processing Time Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (ovms_graph_processing_time_us_bucket)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processing time heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(le) (changes(ovms_graph_processing_time_us_bucket[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processing time histogram",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (ovms_graph_processing_time_us_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing time histogram",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (ovms_graph_processing_time_us_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing time 95th quantile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(ovms_graph_processing_time_us_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}