name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make

    - name: Run clang-format-check
      run: make clang-format-check

    - name: Run cpplint
      run: make cpplint

    - name: Run cppstyle
      run: make cppstyle
